groceries app design
tjagadishqualminds/DotNetAssignment pull request #5
Opened 2024-05-30 12:10 UTC by tjagadishqualminds

2024-06-05 11:20 UTC, AfrinShaik2000 requested changes

2024-06-05 11:20 UTC, qm-afrin commented on GroceriesApp/GroceryappDesign.sql
> +CREATE TABLE Register (
Change the table name to UserDetails

2024-06-05 11:20 UTC, qm-afrin commented on GroceriesApp/GroceryappDesign.sql
> +CREATE TABLE [Login](
Remove login table and add the required columns in UserDetails table.

2024-06-05 11:20 UTC, qm-afrin commented on GroceriesApp/GroceryappDesign.sql
> + CONSTRAINT FK_Products_Products_Supplier FOREIGN KEY(ProductSupplierId) REFERENCES Products_Supplier(ProductSupplierId),
First declare the Products_Supplier table and then use it.

2024-06-05 11:20 UTC, qm-afrin commented on GroceriesApp/GroceryappDesign.sql
> +CREATE TABLE SupplierDetails (
Remove SupplierDetails table and declare where the user belongs to which type of user in UserDetails table.

2024-06-12 13:28 UTC, AfrinShaik2000 commented on GroceriesApp/GroceryappDesign.sql
> +	UserType VARCHAR(40) NOT NULL,
What is the use of this column? Remove it.

2024-06-12 13:28 UTC, AfrinShaik2000 commented on GroceriesApp/GroceryappDesign.sql
> +    CREATE TABLE Payment (
How are you differentiating this payment is related to which customer?

2024-06-12 13:28 UTC, AfrinShaik2000 commented on GroceriesApp/GroceryappDesign.sql
> +CREATE TABLE [Orders](
How are you differentiating this order belongs to which customer and what they bought?

2024-06-12 13:28 UTC, AfrinShaik2000 commented on GroceriesApp/GroceryappDesign.sql
> + ProductsId INT IDENTITY(1,1),
What is the difference between Products table and Products_Supplier table?

Both have the same information inserted.
For Example: Apple fruit is inserted as the first record in both the tables. Then what is the use of creating two tables?

2024-06-14 06:57 UTC, rojamaddipati commented on GroceriesApp/GroceryappDesign.sql
> +    ConfirmPassword VARCHAR(20) NOT NULL,
you can remove confirmpassword  column
No need of having confirmpassword column we can validate from UI

2024-06-18 12:32 UTC, merged